name: Build and Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: clone
        run: |
          ssh ${{ secrets.USER_IP }} "mkdir -p /opt/bybit"
          ssh ${{ secrets.USER_IP }} "git -C /opt/bybit pull || git clone https://github.com/kppv/bybit.git /opt/bybit"
      - name: run
        run: |          
          ssh ${{ secrets.USER_IP }} bash -c " \
          cd /opt/bybit; \
          export BOT_APP_ID=${{ secrets.BOT_APP_ID }}; \
          export API_HASH=${{ secrets.API_HASH }}; \
          export CHAT_ID=${{ secrets.CHAT_ID }}; \
          export BYBIT_APIKEY=${{ secrets.BYBIT_APIKEY }}; \
          export BYBIT_SECRET=${{ secrets.BYBIT_SECRET }}; \
          cd /opt/bybit && docker compose up --build -d; \
          "